#!/usr/bin/env python3
"""Convert the checked-in Chromium vector paths to CSS masks, without scaling padding twice."""
from pathlib import Path
from urllib.parse import quote
import re
root = Path(__file__).resolve().parents[1]
commands = {'MOVE_TO':'M','R_MOVE_TO':'m','LINE_TO':'L','R_LINE_TO':'l','H_LINE_TO':'H','R_H_LINE_TO':'h','V_LINE_TO':'V','R_V_LINE_TO':'v','CUBIC_TO':'C','R_CUBIC_TO':'c','CUBIC_TO_SHORTHAND':'S','R_CUBIC_TO_SHORTHAND':'s','QUADRATIC_TO':'Q','R_QUADRATIC_TO':'q','ARC_TO':'A','R_ARC_TO':'a','CLOSE':'Z'}

def svg(filename, canvas):
    source = (root/'themes/chromium'/filename).read_text()
    selected = False
    path = []
    for line in source.splitlines():
        line = line.split('//')[0].strip().rstrip(',')
        if not line:
            continue
        values = [x.strip().removesuffix('f') for x in line.split(',')]
        command, args = values[0], values[1:]
        if command == 'CANVAS_DIMENSIONS':
            if selected:
                break
            selected = int(args[0]) == canvas
        elif selected and command not in ('FILL_RULE_NONZERO','FLIPS_IN_RTL','NEW_PATH'):
            if command not in commands:
                raise ValueError(command)
            path.append(commands[command]+' '.join(args))
    assert path, filename
    data = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {canvas} {canvas}"><path fill="black" fill-rule="nonzero" d="{" ".join(path)}"/></svg>'
    return 'url("data:image/svg+xml,'+quote(data,safe='')+'")'

specs = [
    ('#browser .toolbar-addressbar [data-name="Back"] .button-icon', 'arrow_back.icon',24,20),
    ('#browser .toolbar-addressbar [data-name="Forward"] .button-icon', 'arrow_forward.icon',24,20),
    ('#browser .toolbar-addressbar [data-name="Reload"] .button-icon', 'refresh.icon',24,20),
    ('#browser .toolbar-addressbar .UrlBar-AddressField:not(:focus-within):not(:has(.OmniDropdown)) .SiteInfoButton > button[title="Site info"] .button-icon', 'page_info_custom.icon',24,16),
    ('#browser .toolbar-addressbar .UrlBar-AddressField:not(:focus-within):not(:has(.OmniDropdown)) .SiteInfoButton.warning > button .button-icon', 'warning.icon',20,16),
    ('#browser .toolbar-addressbar .UrlBar-AddressField:not(:focus-within):not(:has(.OmniDropdown)) .SiteInfoButton.insecure > button .button-icon', 'dangerous_filled.icon',20,16),
    ('#browser .toolbar-addressbar [data-name="Extensions"] .button-icon', 'extension_chrome_refresh_old.icon',20,20),
    ('#browser .toolbar-addressbar [data-name="ReadingList"] .button-icon', 'reading_list_old.icon',20,20),
    ('#browser .toolbar-addressbar [data-name="DownloadButton"] .button-icon', 'download_toolbar_button_chrome_refresh_old.icon',20,20),
    ('#browser .toolbar-addressbar .BookmarkButton-Button .button-icon', 'star_chrome_refresh_old.icon',20,20),
    ('#browser.tabs-top .newtab .button-icon','add.icon',16,20),
]
css = ['/* Generated by tools/build_icons.py from Chromium BSD-licensed vectors. */']
for selector,filename,canvas,size in specs:
    css += [f'{selector} {{ width:{size}px !important; height:{size}px !important; flex:0 0 {size}px; background:currentColor; mask:{svg(filename,canvas)} center / contain no-repeat; }}',f'{selector} > svg {{ visibility:hidden; }}']
css += [f'#browser .toolbar-addressbar > button.vivaldi::after {{ content:""; width:20px; height:20px; background:currentColor; mask:{svg("more_vert.icon",20)} center / contain no-repeat; pointer-events:none; }}']
css += [f'#browser .toolbar-addressbar [data-name="Reload"] button[title^="Stop"] .button-icon {{ mask:{svg("close.icon",24)} center / contain no-repeat; }}']
css += [f'#browser.tabs-top .toolbar-tabbar-before [data-name="TabButton"]::after {{ border:0 !important; transform:none !important; width:16px; height:16px; background:currentColor; mask:{svg("expand_more_old.icon",16)} center / contain no-repeat; filter:drop-shadow(.25px 0 currentColor) drop-shadow(-.25px 0 currentColor); }}']
css += ['#browser.tabs-top #tabs-container.top .tab .close > svg { visibility:hidden; }', f'#browser.tabs-top #tabs-container.top .tab .close::after {{ content:""; width:15px !important; height:15px !important; flex:0 0 15px; background:currentColor; mask:{svg("close_weight500.icon",24)} center / contain no-repeat; filter:drop-shadow(.2px 0 currentColor) drop-shadow(-.2px 0 currentColor); }}']
css += [f'#browser .toolbar-addressbar .BookmarkButton .button-on .button-icon {{ mask:{svg("star_active_chrome_refresh_old.icon",20)} center / contain no-repeat; }}']
css += ['#browser .bookmark-bar .bookmarkbarItem.folder > .folder-icon { display:none !important; }', f'#browser .bookmark-bar .bookmarkbarItem.folder::before {{ content:""; width:16px; height:16px; flex:0 0 16px; background:currentColor; mask:{svg("folder_chrome_refresh_old.icon",20)} center / contain no-repeat; }}']
css += ['#browser .toolbar-addressbar [data-name="AccountButton"] img[src*="IDR_PROFILE_VIVALDI_AVATAR"] { display:none !important; }', f'#browser .toolbar-addressbar [data-name="AccountButton"]:has(img[src*="IDR_PROFILE_VIVALDI_AVATAR"])::after {{ content:""; width:22px; height:22px; flex:0 0 22px; background:currentColor; mask:{svg("account_circle_outline.icon",20)} center / contain no-repeat; }}']
(root/'nochrome/icons.css').write_text(('\n'.join(css)+'\n').replace('#browser ', '#browser#browser ').replace('#browser.tabs-top', '#browser#browser.tabs-top'))
print('Generated icons.css')
