#!/usr/bin/env python3
"""Convert the checked-in Chromium vector paths to CSS masks, without scaling padding twice."""
from pathlib import Path
from urllib.parse import quote
import re
root = Path(__file__).resolve().parents[1]
commands = {'MOVE_TO':'M','R_MOVE_TO':'m','LINE_TO':'L','R_LINE_TO':'l','H_LINE_TO':'H','R_H_LINE_TO':'h','V_LINE_TO':'V','R_V_LINE_TO':'v','CUBIC_TO':'C','R_CUBIC_TO':'c','ARC_TO':'A','R_ARC_TO':'a','CLOSE':'Z'}

def svg(filename, canvas):
    source = (root/'themes/chromium'/filename).read_text()
    selected = False
    path = []
    for line in source.splitlines():
        line = line.split('//')[0].strip().rstrip(',')
        if not line:
            continue
        values = [x.strip().removesuffix('f') for x in line.split(',')]
        command, args = values[0], values[1:]
        if command == 'CANVAS_DIMENSIONS':
            if selected:
                break
            selected = int(args[0]) == canvas
        elif selected and command not in ('FILL_RULE_NONZERO','FLIPS_IN_RTL'):
            if command not in commands:
                raise ValueError(command)
            path.append(commands[command]+' '.join(args))
    assert path, filename
    data = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {canvas} {canvas}"><path fill="black" fill-rule="nonzero" d="{" ".join(path)}"/></svg>'
    return 'url("data:image/svg+xml,'+quote(data,safe='')+'")'

specs = [
    ('#browser .toolbar-addressbar [data-name="ReadingList"] .button-icon', 'reading_list_old.icon',20,20),
    ('#browser .toolbar-addressbar [data-name="DownloadButton"] .button-icon', 'download_toolbar_button_chrome_refresh_old.icon',20,20),
    ('#browser.tabs-top .newtab .button-icon','add.icon',16,24),
]
css = ['/* Generated by tools/build_icons.py from Chromium BSD-licensed vectors. */']
for selector,filename,canvas,size in specs:
    css += [f'{selector} {{ width:{size}px !important; height:{size}px !important; flex:0 0 {size}px; background:currentColor; mask:{svg(filename,canvas)} center / contain no-repeat; }}',f'{selector} > svg {{ visibility:hidden; }}']
css += [f'#browser .toolbar-addressbar > button.vivaldi::after {{ content:""; width:20px; height:20px; background:currentColor; mask:{svg("more_vert.icon",20)} center / contain no-repeat; pointer-events:none; }}']
css += [f'#browser .folder-icon {{ width:20px !important; height:20px !important; flex:0 0 20px; background:currentColor; mask:{svg("folder_chrome_refresh_old.icon",20)} center / contain no-repeat; }}', '#browser .folder-icon > * { visibility:hidden; }']
(root/'nochrome/icons.css').write_text(('\n'.join(css)+'\n').replace('#browser ', '#browser#browser ').replace('#browser.tabs-top', '#browser#browser.tabs-top'))
print('Generated icons.css')
